name: GitHub Classroom Workflow

on: [push]

jobs:
  build:
    permissions: write-all
    name: Autograding
    runs-on: self-hosted
    steps:
      - name: Check-in Student Repo
        uses: actions/checkout@v2
      
      - name: Check-in Clean Test Collateral
        uses: actions/checkout@v2
        with:
          repository: CSCE313-Tyagi/public-tests
          path: tests
      
      - name: Set-up Autograder Environment
        run: |
          mkdir .github/classroom/
          cp tests/graders/grading_SA3.json .github/classroom/autograding.json
          cp tests/makefiles/makefile_SA3A A/makefile
          cp tests/makefiles/makefile_SA3B B/makefile
          cp tests/makefiles/makefile_SA3C C/makefile
          cp tests/collateral/SA3A-tests/* A/test-files/
          cp tests/collateral/SA3B-tests/* B/test-files/
          cp tests/collateral/SA3C-tests/* C/test-files/
      - name: Run Autograder
        uses: education/autograding@v1